import { word } from "./types";

export const hiragana : word[] = [
    new word("あ", "a", "a"),
    new word("い", "i", "ee"),
    new word("う", "u", "oo"),
    new word("え", "e", "e"),
    new word("お", "o", "o"),
    new word("か", "ka", "ka"),
    new word("き", "ki", "ki"),
    new word("く", "ku", "ku"),
    new word("け", "ke", "ke"),
    new word("こ", "ko", "ko"),
    new word("さ", "sa", "sa"),
    new word("し", "shi", "shi"),
    new word("す", "su", "su"),
    new word("せ", "se", "se"),
    new word("そ", "so", "so"),
    new word("た", "ta", "ta"),
    new word("ち", "chi", "chi"),
    new word("つ", "tsu", "tsu"),
    new word("て", "te", "te"),
    new word("と", "to", "to"),
    new word("な", "na", "na"),
    new word("に", "ni", "ni"),
    new word("ぬ", "nu", "nu"),
    new word("ね", "ne", "ne"),
    new word("の", "no", "no"),
    new word("は", "ha", "ha"),
    new word("ひ", "hi", "hi"),
    new word("ふ", "fu", "fu"),
    new word("へ", "he", "he"),
    new word("ほ", "ho", "ho"),
    new word("ま", "ma", "ma"),
    new word("み", "mi", "mi"),
    new word("む", "mu", "mu"),
    new word("め", "me", "me"),
    new word("も", "mo", "mo"),
    new word("ら", "ra", "ra"),
    new word("り", "ri", "ri"),
    new word("る", "ru", "ru"),
    new word("れ", "re", "re"),
    new word("ろ", "ro", "ro"),
    new word("や", "ya", "ya"),
    new word(""),
    new word("ゆ", "yu", "yu"),
    new word(""),
    new word("よ", "yo", "yo"),
    new word("わ", "wa", "wa"),
    new word(""),
    new word(""),
    new word(""),
    new word("を", "wo", "wo"),
    new word("ん", "n", "n"),
    new word(""),
    new word(""),
    new word(""),
    new word("")
  ];