import { word } from "./types";

export const hiragana : word[] = [
    new word("あ", "a", "a"),
    new word("い", "i", "ee"),
    new word("う", "u", "oo"),
    new word("え", "e", "e"),
    new word("お", "o", "o"),
    new word("か", "ka", "ka"),
    new word("き", "ki", "ki"),
    new word("く", "ku", "ku"),
    new word("け", "ke", "ke"),
    new word("こ", "ko", "ko"),
    new word("さ", "sa", "sa"),
    new word("し", "shi", "shi"),
    new word("す", "su", "su"),
    new word("せ", "se", "se"),
    new word("そ", "so", "so"),
    new word("た", "ta", "ta"),
    new word("ち", "chi", "chi"),
    new word("つ", "tsu", "tsu"),
    new word("て", "te", "te"),
    new word("と", "to", "to"),
    new word("な", "na", "na"),
    new word("に", "ni", "ni"),
    new word("ぬ", "nu", "nu"),
    new word("ね", "ne", "ne"),
    new word("の", "no", "no"),
    new word("は", "ha", "ha"),
    new word("ひ", "hi", "hi"),
    new word("ふ", "fu", "fu"),
    new word("へ", "he", "he"),
    new word("ほ", "ho", "ho"),
    new word("ま", "ma", "ma"),
    new word("み", "mi", "mi"),
    new word("む", "mu", "mu"),
    new word("め", "me", "me"),
    new word("も", "mo", "mo"),
    new word("ら", "ra", "ra"),
    new word("り", "ri", "ri"),
    new word("る", "ru", "ru"),
    new word("れ", "re", "re"),
    new word("ろ", "ro", "ro"),
    new word("や", "ya", "ya"),
    new word(""),
    new word("ゆ", "yu", "yu"),
    new word(""),
    new word("よ", "yo", "yo"),
    new word("わ", "wa", "wa"),
    new word(""),
    new word(""),
    new word(""),
    new word("を", "wo", "wo"),
    new word("ん", "n", "n"),
    new word(""),
    new word(""),
    new word(""),
    new word("")
  ];

  export const katakana : word[] = [
    new word("ア", "a", "a"),
    new word("イ", "i", "ee"),
    new word("ゥ", "u", "oo"),
    new word("エ", "e", "e"),
    new word("オ", "o", "o"),
    new word("カ", "ka", "ka"),
    new word("キ", "ki", "ki"),
    new word("ク", "ku", "ku"),
    new word("ケ", "ke", "ke"),
    new word("コ", "ko", "ko"),
    new word("サ", "sa", "sa"),
    new word("シ", "shi", "shi"),
    new word("ス", "su", "su"),
    new word("セ", "se", "se"),
    new word("ソ", "so", "so"),
    new word("タ", "ta", "ta"),
    new word("チ", "chi", "chi"),
    new word("ツ", "tsu", "tsu"),
    new word("テ", "te", "te"),
    new word("ト", "to", "to"),
    new word("ナ", "na", "na"),
    new word("二", "ni", "ni"),
    new word("ヌ", "nu", "nu"),
    new word("ネ", "ne", "ne"),
    new word("ノ", "no", "no"),
    new word("ハ", "ha", "ha"),
    new word("ヒ", "hi", "hi"),
    new word("フ", "fu", "fu"),
    new word("ヘ", "he", "he"),
    new word("ホ", "ho", "ho"),
    new word("マ", "ma", "ma"),
    new word("ミ", "mi", "mi"),
    new word("ム", "mu", "mu"),
    new word("メ", "me", "me"),
    new word("モ", "mo", "mo"),
    new word("ラ", "ra", "ra"),
    new word("リ", "ri", "ri"),
    new word("ル", "ru", "ru"),
    new word("レ", "re", "re"),
    new word("ロ", "ro", "ro"),
    new word("ャ", "ya", "ya"),
    new word(""),
    new word("ュ", "yu", "yu"),
    new word(""),
    new word("ヨ", "yo", "yo"),
    new word("ワ", "wa", "wa"),
    new word(""),
    new word(""),
    new word(""),
    new word("ヲ", "wo", "wo"),
    new word("ン", "n", "n"),
    new word(""),
    new word(""),
    new word(""),
    new word("")
  ];